[package]
name = "bitcoin-wallet-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
otc-models = { workspace = true }
clap = { workspace = true }
argon2 = { workspace = true }
uuid = { workspace = true }
serde_json = { workspace = true }
dialoguer = { workspace = true }
rand = { workspace = true }
snafu = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
blockchain-utils = { workspace = true }