[package]
name = "otc-protocols"
version.workspace = true
edition.workspace = true

[dependencies]
otc-models = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
alloy = { workspace = true }
snafu = { workspace = true }